import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContactList from '../components/contacts/ContactList'
import styles from '../styles/Home.module.css'

const Home: NextPage = (props) => {
   const [contacts, setContacts] = useState([])

 // const {contacts} = useContacts()

  useEffect(() => {
    axios.get('/api/contacts').then((resp) => setContacts(resp.data))
  }, [])
  return (
    <>
      <Head>
        <title>Contact List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactList contacts={contacts} />
    </>
  )
}

// export async function getStaticProps(){
//   // axios
//   // .get('http://localhost:8000/contacts')
//   // .then((resp) => setContacts(resp.data))
//   return {
//     props: {
//       contacts: contacts
//     },
//     revalidate: 10
//   }
// }

export default Home
