#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before commiting'

npm run check-types || {
  echo 'Failed type check'
  false;
}

npm run check-format || {
  echo 'Failed format check'
  false;
}

npm run check-lint || {
  echo 'Failed lint check'
  false;
}

echo 'Build now'

npm run build || {
  echo 'Build failed'
  false;
}

echo 'Commiting...'

npm test
